# Generated by Django 4.2.7 on 2026-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Unix timestamp when job was posted'),
        ),
    ]
