# Generated by Django 4.2.7 on 2026-05-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperstate',
            name='worker_pid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
