"""
Django settings for jobscraper project.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-ev2v8)lpuedaa%r*zbq)+jm3z8omymu%pox)rd1*+sn5hxqn)s",
)

DEBUG = True
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "jobs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jobscraper.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jobscraper.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 60,
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ALLOWED_ATS = [
    "greenhouse.io",
    "lever.co",
    "myworkdayjobs.com",
    "myworkdaysite.com",
    "ashbyhq.com",
    "smartrecruiters.com",
    "bamboohr.com",
    "icims.com",
    "jobvite.com",
    "taleo.net",
    "oraclecloud.com",
    "successfactors.com",
    "pinpointhq.com",
    "amazon.jobs",
    "careers.microsoft.com",
]

MAX_PAGES_PER_KEYWORD = 40

KEYWORDS = [
    # Software Engineering
    "Software engineer",
    "Software developer",
    "Software Engineer I",
    "Software Engineer II",
    "Associate software engineer",
    "Junior software engineer",
    "Graduate software engineer",
    "Entry level software engineer",
    "Software programmer",
    "Programmer analyst",
    "Application developer",
    "Applications engineer",
    "Enterprise application developer",
    "API developer",
    "API engineer",
    "API integration engineer",
    "Middleware developer",
    "Distributed systems engineer",
    "Systems software engineer",
    "Core software engineer",
    "Infrastructure software engineer",
    "Platform engineer",
    "System engineer",
    "Microservices engineer",
    "Django developer",
    "Firmware engineer",
    "Hardware engineer",
    # Backend
    "Backend developer",
    "Backend engineer",
    "Java developer",
    "Java backend developer",
    "Java engineer",
    "Spring Boot developer",
    "Spring developer",
    "REST API developer",
    "JVM engineer",
    "Kotlin backend developer",
    "Python developer",
    "Python backend developer",
    "Go developer",
    "Golang developer",
    "Rust developer",
    "Node.js developer",
    "PHP developer",
    "Ruby developer",
    "Scala developer",
    "C# backend developer",
    # Frontend
    "Frontend developer",
    "Frontend engineer",
    "React developer",
    "React engineer",
    "Angular developer",
    "Vue developer",
    "Javascript developer",
    "Typescript developer",
    "Web developer",
    "UI engineer",
    "Web application developer",
    "Next.js developer",
    "Frontend architect",
    # Full Stack
    "Full stack developer",
    "Full stack engineer",
    "MERN stack developer",
    "MEAN stack developer",
    "Java full stack developer",
    "Python full stack developer",
    ".NET full stack developer",
    "Full stack JavaScript developer",
    "Web application engineer",
    ".NET developer",
    "Power Platform developer",
    # Mobile
    "iOS developer",
    "iOS engineer",
    "Android developer",
    "Android engineer",
    "React native developer",
    "React native engineer",
    "Flutter developer",
    "Flutter engineer",
    "Swift developer",
    "SwiftUI developer",
    "Objective-C developer",
    "Kotlin developer",
    "Mobile developer",
    "Mobile application developer",
    "Mobile engineer",
    "Cross platform developer",
    "Xamarin developer",
    "Ionic developer",
    # Cloud & DevOps
    "Cloud engineer",
    "Cloud developer",
    "Cloud architect",
    "Cloud consultant",
    "Devops engineer",
    "DevSecOps engineer",
    "AWS engineer",
    "AWS cloud engineer",
    "AWS DevOps engineer",
    "AWS Java developer",
    "Azure engineer",
    "Azure cloud engineer",
    "GCP engineer",
    "Google cloud engineer",
    "Cloud infrastructure engineer",
    "Cloud platform engineer",
    "Site reliability engineer",
    "Infrastructure engineer",
    "Kubernetes engineer",
    "Docker engineer",
    "Terraform engineer",
    "Platform operations engineer",
    "Platform reliability engineer",
    "Release engineer",
    "Build engineer",
    "CI/CD engineer",
    "Observability engineer",
    # AI / ML
    "AI engineer",
    "AI developer",
    "AI software engineer",
    "Machine learning engineer",
    "Machine learning scientist",
    "ML research engineer",
    "Deep learning engineer",
    "NLP engineer",
    "Computer vision engineer",
    "Prompt engineer",
    "LLM engineer",
    "LLMOps engineer",
    "Generative AI engineer",
    "Gen AI",
    "Applied AI engineer",
    "AI research engineer",
    "AI research scientist",
    "Applied scientist",
    "Research scientist",
    "Research engineer",
    "AI platform engineer",
    "AI infrastructure engineer",
    "AI safety engineer",
    "MLOps engineer",
    "ML platform engineer",
    "Data science engineer",
    "AI solutions engineer",
    "Reinforcement learning engineer",
    # Data
    "Data analyst",
    "Data engineer",
    "Data science",
    "Data scientist",
    "Analytics engineer",
    "Data analytics engineer",
    "Analytics consultant",
    "Business intelligence analyst",
    "BI developer",
    "Reporting analyst",
    "Tableau developer",
    "Tableau analyst",
    "Power BI developer",
    "SQL developer",
    "SQL analyst",
    "ETL developer",
    "ETL engineer",
    "Database engineer",
    "Database developer",
    "Database administrator",
    "Big data engineer",
    "Hadoop developer",
    "Spark developer",
    "Data warehouse engineer",
    "Snowflake developer",
    "Data architect",
    "Data modeler",
    "Data platform engineer",
    "Data governance analyst",
    "Data quality analyst",
    "Streaming engineer",
    "MongoDB developer",
    "PostgreSQL developer",
    # Security
    "Security engineer",
    "Cybersecurity analyst",
    "Security analyst",
    "Cyber security engineer",
    "Cyber security consultant",
    "Security consultant",
    "Application security engineer",
    "Network security engineer",
    "Information security analyst",
    "SOC analyst",
    "SOC engineer",
    "Security operations analyst",
    "Incident response engineer",
    "Threat analyst",
    "Threat hunter",
    "Penetration tester",
    "Ethical hacker",
    "Vulnerability analyst",
    "IAM engineer",
    "Identity engineer",
    "Cloud security engineer",
    "Security architect",
    "GRC analyst",
    "Information assurance analyst",
    "AI safety engineer",
    # QA & Testing
    "QA engineer",
    "Test engineer",
    "Software test engineer",
    "Software QA engineer",
    "Automation test engineer",
    "Test automation engineer",
    "QA automation engineer",
    "Automation QA engineer",
    "Manual QA engineer",
    "Manual tester",
    "QA analyst",
    "SDET",
    "Quality engineer",
    "Performance test engineer",
    "Load test engineer",
    "Validation engineer",
    "Verification engineer",
    "Software validation engineer",
    # Networking & Infrastructure
    "Network engineer",
    "Network administrator",
    "Network architect",
    "Systems administrator",
    "IT support engineer",
    "Technical support engineer",
    "Desktop support engineer",
    "Help desk analyst",
    "Technical support specialist",
    "Application support engineer",
    "Production support engineer",
    "Telecom engineer",
    "Voice engineer",
    "NOC engineer",
    "Windows administrator",
    "Linux administrator",
    "Active directory engineer",
    "VMware engineer",
    "Storage engineer",
    # Product & Design
    "Product manager",
    "Associate product manager",
    "Technical product manager",
    "AI product manager",
    "Product owner",
    "Product analyst",
    "UI designer",
    "UX designer",
    "UI UX designer",
    "Product designer",
    "UX researcher",
    "Visual designer",
    "Interaction designer",
    "Motion designer",
    "Graphic designer",
    "Engineering manager",
    "Program manager",
    "Project manager",
    "Technical program manager",
    # Business & Finance
    "Business analyst",
    "Technical business analyst",
    "Business systems analyst",
    "Operations analyst",
    "Finance analyst",
    "Financial analyst",
    "FP&A analyst",
    "Investment analyst",
    "Treasury analyst",
    "Accounting analyst",
    "Risk analyst",
    "Revenue operations analyst",
    "Growth analyst",
    "Marketing analyst",
    "Marketing manager",
    "SEO specialist",
    "Supply chain",
    "Supply chain analyst",
    "Supply chain manager",
    "Procurement specialist",
    "Logistics analyst",
    "Inventory analyst",
    # Solutions & Customer Success
    "Solutions engineer",
    "Solutions architect",
    "Cloud solutions architect",
    "Forward deployed engineer",
    "Customer success engineer",
    "Implementation engineer",
    "Integration engineer",
    "Technical account manager",
    "Sales engineer",
    "Developer advocate",
    "Developer relations engineer",
    # ERP & CRM
    "SAP developer",
    "SAP",
    "SAP MM",
    "SAP EWM",
    "SAP ABAP developer",
    "SAP consultant",
    "SAP functional consultant",
    "SAP technical consultant",
    "SAP FICO consultant",
    "SAP SD consultant",
    "SAP basis administrator",
    "Salesforce developer",
    "Salesforce administrator",
    "Salesforce engineer",
    "Salesforce consultant",
    "Salesforce architect",
    "Salesforce QA",
    "CRM developer",
    "CRM administrator",
    "Dynamics 365 developer",
    "Power Apps developer",
    "Power Automate developer",
    "Microsoft Power Platform consultant",
    "ServiceNow developer",
    "Workday consultant",
    "Oracle developer",
    # Quantitative & Finance Tech
    "Quantitative analyst",
    "Quantitative developer",
    "Quantitative researcher",
    # Epic Systems (Healthcare EHR)
    "Epic analyst",
    "Epic consultant",
    "Epic application analyst",
    "Epic implementation analyst",
    "Epic clinical analyst",
    "Epic build analyst",
    "Epic Prelude analyst",
    "Epic Resolute analyst",
    "Epic Beaker analyst",
    "Epic Cogito analyst",
    "Epic Cupid analyst",
    "Epic Grand Central analyst",
    "Epic Willow analyst",
    "Epic trainer",
    "Epic integration engineer",
    "Epic data analyst",
    # Extended AI / Agentic
    "AI agent engineer",
    "Agentic AI engineer",
    "RAG engineer",
    "Vector database engineer",
    "AI automation engineer",
    "AI workflow engineer",
    "Foundation model engineer",
    "AI integration engineer",
    "LLM application developer",
    "AI application developer",
    "Multimodal AI engineer",
    "AI systems engineer",
    # Blockchain & Web3
    "Blockchain developer",
    "Smart contract developer",
    "Solidity developer",
    "Web3 developer",
    # Game & AR/VR
    "Game developer",
    "Unity developer",
    "Unreal engine developer",
    "Graphics engineer",
    "AR developer",
    "VR developer",
    # Database Specifics
    "SQL server developer",
    "Oracle DBA",
    "PostgreSQL DBA",
    "Database architect",
    # Healthcare & Life Sciences
    "Clinical research scientist",
    "Clinical research associate",
    "Drug safety associate",
    "Clinical data analyst",
    "Biostatistician",
    "Health informatics analyst",
    "Biomedical engineer",
    "Pharmacovigilance analyst",
    "Medical device engineer",
    "Regulatory affairs specialist",
    "Bioinformatics engineer",
    "Computational biologist",
    "Genomics data scientist",
    # Allied Health
    "Physical therapist",
    "Occupational therapist",
    "Speech language pathologist",
    "Radiologic technologist",
    "Medical laboratory scientist",
    # Civil & Construction
    "Civil engineer",
    "Construction engineer",
    "Structural engineer",
    "Geotechnical engineer",
    "Transportation engineer",
    "Environmental engineer",
    "Urban planner",
    "Construction manager",
    # Mechanical & Manufacturing
    "Mechanical engineer",
    "Manufacturing engineer",
    "Process engineer",
    "Industrial engineer",
    "Automation engineer",
    "Materials engineer",
    "Thermal engineer",
    "HVAC engineer",
    "Tooling engineer",
    # Electronics & Electrical
    "Electrical engineer",
    "Electronics engineer",
    "FPGA engineer",
    "PCB designer",
    "Power electronics engineer",
    "Signal processing engineer",
    "RF engineer",
    "Semiconductor engineer",
    "VLSI engineer",
    "Photonics engineer",
    # Aerospace
    "Aerospace engineer",
    "Avionics engineer",
    "Propulsion engineer",
    "Flight software engineer",
    "Autonomous systems engineer",
    # HR & People Operations
    "HR analyst",
    "Human resources analyst",
    "Talent acquisition specialist",
    "Recruiter",
    "Compensation analyst",
    "HR business partner",
    "Workforce analyst",
    "Learning development specialist",
    # Geospatial
    "Geospatial engineer",
    "GIS developer",
    "GIS analyst",
    # Robotics & Embedded
    "Robotics engineer",
    "Robotics software engineer",
    "Embedded systems engineer",
    # Entry Level
    "New grad software engineer",
    "Junior developer",
]

LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "scraper.log",
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "scraper": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
